version: '3.3'
services:
  contact:
    image: johncarnell/contact:latest
    ports:
       - "5000:5000"
    deploy:
      endpoint_mode: vip
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure    
    depends_on:
      - "contactdb"  
    environment:
      POSTGRES_USER:     "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_HOSTNAME: "contactdb"
      POSTGRES_DB:       "contact_db"  

  notifier:
    image: johncarnell/notifier:latest
    ports:
       - "5010:5010"
    deploy:
      endpoint_mode: vip
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure    
    secrets:
      - account_sid
      - auth_token    
    depends_on:
      - "contact"      
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOSTNAME: "${POSTGRES_HOSTNAME}"
      POSTGRES_DB: "${POSTGRES_DB}"  
   
  contactdb:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB:      "${POSTGRES_DB}" 

  logspout:
    image: gliderlabs/logspout
    command: syslog://logs5.papertrailapp.com:35178
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    

secrets:
  account_sid:
    external: true
  auth_token:
    external: true