spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://eagle-eye-aws-dev.cpxog63l4usu.us-west-1.rds.amazonaws.com:5432/eagle_eye_aws_dev"
spring.datasource.username: "postgres_aws_dev"
spring.datasource.password: "{cipher}db4e4e53bbaeba4b10cf4fdc913871d0560d3c8acef2fa3579b1609a83647eb46e337452b6e5dec1ede6ae820df67c3a"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
redis.server: "spmia-tmx-redis-dev.lxxnq4.0001.usw1.cache.amazonaws.com"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
